services:
  db:
    image: postgres:17
    container_name: check-check-auth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: check-check-auth-db
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
